version: '3.4'
services: 

  nginx:
    build:
      dockerfile: ./docker/nginx.Dockerfile
      context: .
    image: raelamorim/nginx
    container_name: nginx
    ports: 
      - "8080:80"
    networks: 
      - prod
    depends_on:
      - "app1"
      - "app2" 
      - "app3"
      - "redis"
      - "mysql_1"

  app1:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app1
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql_1"
      - "redis"

  app2:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app2
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql_1"
      - "redis"
      - "app1"

  app3:
    build:
      dockerfile: ./docker/gonoticias.Dockerfile
      context: .
    image: golang
    container_name: app3
    ports:
      - "8080"
    networks:
      - prod
    depends_on:
      - "mysql_1"
      - "redis"
      - "app2"

  redis:
    image: redis
    container_name: redis
    networks:
      - prod
    depends_on:
      - mysql_1   
    
    expose:      
      - '6379'      

  mysql_1:
    image: mysql
    container_name: mysql_1
    ports: 
      - 33061:3306
    environment:       
      - MYSQL_USER=glauber
      - MYSQL_PASSWORD=exemplo
      - MYSQL_DATABASE=gonoticias
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - prod


networks:
  prod:
    driver: bridge
